import '@styles/globals.css'
import type { Metadata } from 'next'
import Nav from '@components/Nav'
import Footer from '@components/Footer'
import Providers from '@components/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className='app'>
          <Providers>
            <Nav />
              {children}
            <Footer />
          </Providers>
        </main>
      </body>
    </html>
  )
}
